// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kpzxojivkxekgmdepaml.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtwenhvaml2a3hla2dtZGVwYW1sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3MzExNTcsImV4cCI6MjA2NzMwNzE1N30.HAnLSEfZcRVhFkyMgj_vxZCoXlEjNoFdZLgHSwkOZ5s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});